---
- name: Filebeat
  hosts: http
  tasks:
    - name: Install GIT
      become: yes
      yum:
        name: git
        state: present

    - name: Clone Repo
      become: yes
      ansible.builtin.git:
        repo: https://github.com/avo1yanskiy/dist.git
        dest: /tmp/dist
    - name: Install PRM
      become: yes
      yum:
        name: /tmp/dist/filebeat-8.2.2-x86_64.rpm
        state: present
    - name: Copy nginx.yml
      become: yes
      ansible.builtin.copy:
       src: nginx.yml
       dest: /etc/filebeat/modules.d/
    - name: Service FileBeat
      become: yes
      service:
        name: filebeat
        state: started
    

