---
- name: Filebeat
  hosts: http
  tasks:
    - name: Install GIT
      become: yes
      yum:
        name: git
        state: present

    - name: Clone Repo
      become: yes
      ansible.builtin.git:
        repo: https://github.com/avo1yanskiy/dist.git
        dest: /tmp/dist
    - name: Install PRM
      become: yes
      yum:
        name: /tmp/dist/filebeat-7.14.1-x86_64.rpm
        state: present
    - name: Configure filebeat
      become: true
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
    - name: Set filebeat systemwork
      become: true
      command:
        cmd: filebeat modules enable system
    - name: Set filebeat nginx
      become: true
      command:
        cmd: filebeat modules enable nginx
    - name: Service FileBeat
      become: yes
      service:
        name: filebeat
        state: started
    - name: zagruzka Kibana dashboard
      become: true
      command:
        cmd: filebeat setup
        chdir: /usr/share/filebeat/bin
      register: filebeat_setup
      until: filebeat_setup is succeeded
    - name: Service Filebeat-restart
      become: yes
      service:
        name: filebeat
        state: restarted
    - name: Download nginxlog-exporter
      become: yes
      get_url:
        url: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.9.2/prometheus-nginxlog-exporter_1.9.2_linux_amd64.rpm
        dest: /tmp/prometheus-nginxlog-exporter_1.9.2_linux_amd64.rpm
    - name: Install
      become: yes
      yum:
        name: /tmp/prometheus-nginxlog-exporter_1.9.2_linux_amd64.rpm
        state: present
    - name: Copy prometheus-nginxlog-exporter.hcl
      become: yes
      ansible.builtin.copy:
       src: prometheus-nginxlog-exporter.hcl
       dest: /etc/

    - name: Service prometheus-nginxlog-exporter
      become: yes
      service:
        name: prometheus-nginxlog-exporter
        state: started
        