---
- name: Enable EPEL Repository
  hosts: prod
  tasks:
  - name: Enable EPEL Repository on CentOS 8
    become: yes
    dnf:
      name: epel-release
      state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts
      ['distribution_major_version'] == '8'
  - name: Enable EPEL Repository on CentOS 7
    become: yes
    yum:
      name: epel-release
      state: latest
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts
      ['distribution_major_version'] == '7'
      