---
- name: Enable EPEL Repository
  hosts: prod
  tasks:
    - name: Enable EPEL Repository on CentOS 7
      become: yes
      yum:
        name: epel-release
        state: latest
- name: Set a hostname http-1
  hosts: srv
  tasks:
    - name: Set a hostname http-1
      become: yes
      ansible.builtin.shell: echo 'http-1' > /etc/hostname
- name: Set a hostname http-2
  hosts: srv1
  tasks:
    - name: Set a hostname http-2
      become: yes
      ansible.builtin.shell: echo 'http-2' > /etc/hostname
- name: Set a hostname grafana
  hosts: srv2
  tasks:
    - name: Set a hostname grafana
      become: yes
      ansible.builtin.shell: echo 'grafana' > /etc/hostname
- name: Set a hostname prometheus
  hosts: srv3
  tasks:
    - name: Set a hostname prometheus
      become: yes
      ansible.builtin.shell: echo 'prometheus' > /etc/hostname
- name: Set a hostname kibana
  hosts: srv4
  tasks:
    - name: Set a hostname kibana
      become: yes
      ansible.builtin.shell: echo 'kibana' > /etc/hostname
- name: Set a hostname elasticsearch
  hosts: srv5
  tasks:
    - name: Set a hostname elasticsearch
      become: yes
      ansible.builtin.shell: echo 'elasticsearch' > /etc/hostname
- name: Reboot
  hosts: prod
  tasks:
    - name: reboot
      become: yes
      reboot:
  
