---
- name: Enable EPEL Repository
  hosts: prod
  tasks:
    - name: Enable EPEL Repository on CentOS 7
      become: yes
      yum:
        name: epel-release
        state: latest
- name: Set a hostname http-1
  hosts: srv
  tasks:
    - name: Set a hostname http-1
      ansible.builtin.hostname:
        name: http-1
- name: Set a hostname http-2
  hosts: srv1
  tasks:
    - name: Set a hostname http-2
      ansible.builtin.hostname:
        name: http-2
- name: Set a hostname prometheus
  hosts: srv2
  tasks:
    - name: Set a hostname prometheus
      ansible.builtin.hostname:
        name: prometheus
- name: Set a hostname kibana
  hosts: srv3
  tasks:
    - name: Set a hostname kibana
      ansible.builtin.hostname:
        name: kibana
- name: Set a hostname elasticsearch
  hosts: srv4
  tasks:
    - name: Set a hostname elasticsearch
      ansible.builtin.hostname:
        name: elasticsearch