---
- name: Filebeat
  hosts: http
  tasks:
    - name: Install GIT
      become: yes
      yum:
        name: git
        state: present

    - name: Clone Repo
      become: yes
      ansible.builtin.git:
        repo: https://github.com/avo1yanskiy/dist.git
        dest: /tmp/dist
    - name: Install PRM
      become: yes
      yum:
        name: /tmp/dist/filebeat-8.2.2-x86_64.rpm
        state: present
    - name: Copy nginx.yml
      become: yes
      ansible.builtin.copy:
       src: nginx.yml
       dest: /etc/filebeat/modules.d/
    - name: Service FileBeat
      become: yes
      service:
        name: filebeat
        state: started
    - name: Download nginxlog-exporter
      become: yes
      get_url:
        url: https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/download/v1.9.2/prometheus-nginxlog-exporter_1.9.2_linux_amd64.rpm
        dest: /tmp/prometheus-nginxlog-exporter_1.9.2_linux_amd64.rpm
    - name: Install
      become: yes
      yum:
        name: /tmp/prometheus-nginxlog-exporter_1.9.2_linux_amd64.rpm
        state: present

    - name: Service prometheus-nginxlog-exporter
      become: yes
      service:
        name: prometheus-nginxlog-exporter
        state: started

    





    

