version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.4
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'password'