{
 "title": "HTTP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http Response Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app1_http_response_size_bytes{instance=\"192.168.101.6:4040\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Response Count Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app1_http_response_count_total{instance=\"192.168.101.6:4040\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parse errors total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "app1_parse_errors_total{instance=\"192.168.101.6:4040\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status codes per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[5m]))"
    }
   ]
  }
 ]
}