{
 "title": "Server-nginx-statistic",
 "description": "http-web",
 "tags": [
  "web",
  "http",
  "webserver"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "http-1 (webserver)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Response Size Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "app1_http_response_size_bytes{instance=\"192.168.101.6:4040\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Http Response Count Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "app1_http_response_count_total{instance=\"192.168.101.6:4040\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parse errors total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "app1_parse_errors_total{instance=\"192.168.101.6:4040\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status codes per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by(status) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[1m]))"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[1m]))"
      }
     ]
    },
    {
     "title": "HTTP traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "http-2 (webserver)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Response Count Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "app1_http_response_count_total{instance=\"192.168.100.3:4040\"}"
      }
     ]
    },
    {
     "title": "Http Response Size Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "app1_http_response_size_bytes{instance=\"192.168.100.3:4040\"}"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[1m]))"
      }
     ]
    },
    {
     "title": "HTTP traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by(instance) (rate(app1_http_response_count_total{instance=\"192.168.101.6:4040\"}[5m]))"
      }
     ]
    },
    {
     "title": "Status codes per second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(status) (rate(app1_http_response_count_total{instance=\"192.168.100.3:4040\"}[1m]))"
      }
     ]
    },
    {
     "title": "Parse errors total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "app1_parse_errors_total{instance=\"192.168.100.3:4040\"}"
      }
     ]
    }
   ]
  }
 ]
}