{
 "title": "HTTP-WEB-2",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation,  Filesystem usage and Predicted time to filesystems filling",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": {
     "query": "up{job=\"node-exporter\"}"
    }
   },
   { "name": "job", "label": "job", "query": "node-exporter-2" }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.101.6:9100\", job=\"node_exporter-2\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='node_exporter-2',instance='192.168.101.6:9100'} - node_memory_MemFree_bytes{job='node_exporter-2',instance='192.168.101.6:9100'} - node_memory_Buffers_bytes{job='node_exporter-2',instance='192.168.101.6:9100'} - node_memory_Cached_bytes{job='node_exporter-2',instance='192.168.101.6:9100'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job='$job',instance='$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"node_exporter-2\",instance=\"192.168.101.6:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Filesystem Fill Up Time",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job='node_exporter-2',instance='192.168.101.6:9100'} - node_filesystem_free_bytes{job='node_exporter-2',instance='192.168.101.6:9100'}) / deriv(node_filesystem_free_bytes{job='node_exporter-2',instance='192.168.101.6:9100',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''}[3d]) > 0",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job='node_exporter-2',instance='192.168.101.6:9100',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job='node_exporter-2',instance='192.168.101.6:9100',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''} / node_filesystem_size_bytes{job='node_exporter-2',instance='192.168.101.6:9100'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node_exporter-2\",instance=\"192.168.101.6:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  }
 ]
}