---
- name: Enable EPEL Repository
  hosts: prod
  tasks:
  - name: Install nginx
    become: yes
    yum:
      name: nginx
      state: installed
  - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
  - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
  - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
  - name: Service Up
    become: yes
    service:
      name: nginx
      state: started
  
  
      