---
- name: Enable EPEL Repository
  hosts: prod
  tasks:
  - name: Install nginx
    become: yes
    yum:
      name: nginx
      state: installed
  - name: Service Up
    become: yes
    service:
      name: nginx
      state: started
  
  
      