---
- name: Enable EPEL Repository
  hosts: http
  tasks:
  - name: Install nginx
    become: yes
    yum:
      name: nginx
      state: installed
  - name: copy index.html
    become: yes
    template:
      src=templates/index.html.j2 
      dest=/usr/share/nginx/html/index.html
      mode=0644
  - name: Service Up
    become: yes
    service:
      name: nginx
      state: started
  
  
      